// This file was generated by PermissionsDispatcher. Do not modify!
package com.auto.sms.SmsBlaster;

import androidx.annotation.NonNull;
import androidx.core.app.ActivityCompat;

import com.auto.sms.activities.MsgSettingActivity;

import java.lang.String;
import permissions.dispatcher.PermissionUtils;

public final class AnaActivityPermissionsDispatcher {
  private static final int REQUEST_REHBERYUKLE = 0;

  private static final String[] PERMISSION_REHBERYUKLE = new String[] {"android.permission.READ_CONTACTS"};

  private AnaActivityPermissionsDispatcher() {
  }

  static void RehberYukleWithPermissionCheck(@NonNull AnaActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_REHBERYUKLE)) {
      target.RehberYukle();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_REHBERYUKLE, REQUEST_REHBERYUKLE);
    }
  }

  public static void RehberYukleWithPermissionCheck(@NonNull MsgSettingActivity target) {
    if (PermissionUtils.hasSelfPermissions(target, PERMISSION_REHBERYUKLE)) {
      target.RehberYukle();
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_REHBERYUKLE, REQUEST_REHBERYUKLE);
    }
  }

  static void onRequestPermissionsResult(@NonNull AnaActivity target, int requestCode,
      int[] grantResults) {
    switch (requestCode) {
      case REQUEST_REHBERYUKLE:
      if (PermissionUtils.verifyPermissions(grantResults)) {
        target.RehberYukle();
      }
      break;
      default:
      break;
    }
  }
}
